#!/usr/bin/env python3
"""Evaluate the conservative CDSG hard-match agent for M3-3A.

This is a deterministic coverage and traceability evaluation. It intentionally
does not report learned-model accuracy/F1 because the strong-silver labels are
generated by the same CDSG reference.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.pipeline.schema_validator import validate_instance


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as fp:
        for line in fp:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def _load_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as fp:
        return list(csv.DictReader(fp))


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fp:
        writer = csv.DictWriter(fp, fieldnames=fieldnames, extrasaction="ignore", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def _rate(numerator: int | float, denominator: int | float) -> str:
    if not denominator:
        return "0.000000"
    return f"{float(numerator) / float(denominator):.6f}"


def _pct(numerator: int | float, denominator: int | float) -> str:
    if not denominator:
        return "0.0%"
    return f"{float(numerator) / float(denominator) * 100:.1f}%"


def _clean_label(value: Any) -> str:
    if value is None or value == "":
        return "None"
    return str(value)


def _is_abstained(row: dict[str, Any]) -> bool:
    reason = row.get("abstention_reason")
    return reason not in {None, "", "None"}


def _evidence_overall(row: dict[str, Any]) -> str:
    evidence = row.get("evidence_quality")
    if isinstance(evidence, dict):
        return _clean_label(evidence.get("overall"))
    return _clean_label(evidence)


def _schema_valid(row: dict[str, Any]) -> bool:
    existing_errors = row.get("recommendation_schema_errors")
    if existing_errors is not None and existing_errors != "":
        return not bool(existing_errors)
    recommendation = row.get("recommendation_object")
    if isinstance(recommendation, dict):
        return not validate_instance(recommendation, "module3_recommendation_schema.json")
    return False


def _nonempty(row: dict[str, Any], key: str) -> bool:
    value = row.get(key)
    return isinstance(value, list) and bool(value)


def _distribution_rows(
    rows: list[dict[str, Any]],
    total_cases: int,
    scope: str,
    dimensions: list[tuple[str, str]],
) -> list[dict[str, Any]]:
    output_rows: list[dict[str, Any]] = []
    scope_total = len(rows)
    for dimension, key in dimensions:
        counter: Counter[str] = Counter()
        for row in rows:
            if key == "evidence_quality_overall":
                label = _evidence_overall(row)
            else:
                label = _clean_label(row.get(key))
            counter[label] += 1
        for label, count in sorted(counter.items()):
            output_rows.append(
                {
                    "scope": scope,
                    "dimension": dimension,
                    "label": label,
                    "count": count,
                    "fraction_within_scope": _rate(count, scope_total),
                    "fraction_of_total": _rate(count, total_cases),
                }
            )
    return output_rows


def _abstention_rows(records: list[dict[str, Any]], total: int) -> list[dict[str, Any]]:
    abstained = [row for row in records if _is_abstained(row)]
    abstention_total = len(abstained)
    reason_counter = Counter(_clean_label(row.get("abstention_reason")) for row in abstained)
    missing_counter: Counter[str] = Counter()
    for row in abstained:
        missing_items = row.get("missing_information") or row.get("missing_info") or []
        for item in missing_items:
            missing_counter[_clean_label(item)] += 1

    rows: list[dict[str, Any]] = []
    for label, count in sorted(reason_counter.items()):
        rows.append(
            {
                "dimension": "abstention_reason",
                "label": label,
                "count": count,
                "fraction_of_abstentions": _rate(count, abstention_total),
                "fraction_of_total": _rate(count, total),
            }
        )
    for label, count in sorted(missing_counter.items()):
        rows.append(
            {
                "dimension": "missing_information",
                "label": label,
                "count": count,
                "fraction_of_abstentions": _rate(count, abstention_total),
                "fraction_of_total": _rate(count, total),
            }
        )
    return rows


def _conflict_rows(summary_rows: list[dict[str, str]]) -> list[dict[str, Any]]:
    output_rows: list[dict[str, Any]] = []
    for row in summary_rows:
        metric = row.get("metric", "")
        value = row.get("value", "")
        if metric.startswith("field."):
            dimension = "conflict_field"
            label = metric.removeprefix("field.")
            interpretation = "candidate fact disagreement by field"
        elif metric.startswith("risk_level."):
            dimension = "risk_level"
            label = metric.removeprefix("risk_level.")
            interpretation = "risk level assigned by conflict audit"
        elif metric.startswith("resolution."):
            dimension = "resolution_path"
            label = metric.removeprefix("resolution.")
            interpretation = "candidate resolution category"
        else:
            dimension = "overall"
            label = metric
            interpretation = "overall conflict audit count"
        output_rows.append(
            {
                "dimension": dimension,
                "label": label,
                "count": value,
                "interpretation": interpretation,
            }
        )
    return output_rows


def _aggregation_appendix_rows(rows: list[dict[str, str]]) -> list[dict[str, Any]]:
    output_rows: list[dict[str, Any]] = []
    for row in rows:
        strategy = row.get("strategy", "")
        risk_note = row.get("risk_note", "")
        adopted = "no"
        if strategy == "confidence_gated_same_note_union":
            status = "appendix_only_low_risk_diagnostic"
        elif risk_note == "high_risk":
            status = "not_adopted_high_fact_mismatch_risk"
        else:
            status = "appendix_only_not_official_v2"
        output = dict(row)
        output["adopted_in_conservative_v2"] = adopted
        output["m3a_status"] = status
        output_rows.append(output)
    return output_rows


def _metric_row(metric: str, value: Any, count: Any = "", denominator: Any = "", rate: str = "", note: str = "") -> dict[str, Any]:
    return {
        "metric": metric,
        "value": value,
        "count": count,
        "denominator": denominator,
        "rate": rate,
        "note": note,
    }


def _coverage_summary(records: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    total = len(records)
    actionable = [row for row in records if not _is_abstained(row)]
    abstained = [row for row in records if _is_abstained(row)]
    schema_valid = sum(1 for row in records if _schema_valid(row))
    anchor_nonempty = sum(1 for row in records if _nonempty(row, "guideline_anchor"))
    reasoning_nonempty = sum(1 for row in records if _nonempty(row, "reasoning_path"))
    decision_nonempty = sum(1 for row in records if _nonempty(row, "decision_path"))
    visited_nonempty = sum(1 for row in records if _nonempty(row, "visited_nodes"))

    action_total = len(actionable)
    action_schema_valid = sum(1 for row in actionable if _schema_valid(row))
    action_anchor = sum(1 for row in actionable if _nonempty(row, "guideline_anchor"))
    action_reasoning = sum(1 for row in actionable if _nonempty(row, "reasoning_path"))
    action_decision = sum(1 for row in actionable if _nonempty(row, "decision_path"))

    graph_versions = sorted({_clean_label(row.get("cdsg_graph_version")) for row in records})
    graph_ids = sorted({_clean_label(row.get("cdsg_graph_id")) for row in records})

    rows = [
        _metric_row("total_cases", total, total, "", "", "full conservative v2 set"),
        _metric_row("actionable_count", len(actionable), len(actionable), total, _rate(len(actionable), total), "terminal CDSG recommendation without abstention"),
        _metric_row("abstention_count", len(abstained), len(abstained), total, _rate(len(abstained), total), "conservative abstention on missing critical facts"),
        _metric_row("schema_valid_count", schema_valid, schema_valid, total, _rate(schema_valid, total), "module3 recommendation schema"),
        _metric_row("guideline_anchor_nonempty_count", anchor_nonempty, anchor_nonempty, total, _rate(anchor_nonempty, total), "full set"),
        _metric_row("reasoning_path_nonempty_count", reasoning_nonempty, reasoning_nonempty, total, _rate(reasoning_nonempty, total), "full set"),
        _metric_row("decision_path_nonempty_count", decision_nonempty, decision_nonempty, total, _rate(decision_nonempty, total), "full set"),
        _metric_row("visited_nodes_nonempty_count", visited_nonempty, visited_nonempty, total, _rate(visited_nonempty, total), "full set"),
        _metric_row("actionable_schema_valid_count", action_schema_valid, action_schema_valid, action_total, _rate(action_schema_valid, action_total), "actionable subset"),
        _metric_row("actionable_guideline_anchor_nonempty_count", action_anchor, action_anchor, action_total, _rate(action_anchor, action_total), "actionable subset"),
        _metric_row("actionable_reasoning_path_nonempty_count", action_reasoning, action_reasoning, action_total, _rate(action_reasoning, action_total), "actionable subset"),
        _metric_row("actionable_decision_path_nonempty_count", action_decision, action_decision, action_total, _rate(action_decision, action_total), "actionable subset"),
        _metric_row("cdsg_graph_version", "|".join(graph_versions), "", "", "", "deterministic graph version"),
        _metric_row("cdsg_graph_id", "|".join(graph_ids), "", "", "", "deterministic graph id"),
        _metric_row("aggregation_adopted", "no", "", "", "", "conservative v2 does not adopt high-risk aggregation"),
        _metric_row("learned_metric_reported", "no", "", "", "", "strong-silver labels are CDSG-generated references"),
    ]
    stats = {
        "total": total,
        "actionable": len(actionable),
        "abstained": len(abstained),
        "schema_valid": schema_valid,
        "anchor_nonempty": anchor_nonempty,
        "reasoning_nonempty": reasoning_nonempty,
        "decision_nonempty": decision_nonempty,
        "visited_nonempty": visited_nonempty,
        "actionable_rows": actionable,
        "abstained_rows": abstained,
        "graph_versions": graph_versions,
        "graph_ids": graph_ids,
    }
    return rows, stats


def _lookup_count(rows: list[dict[str, Any]], dimension: str, label: str) -> int:
    for row in rows:
        if row.get("dimension") == dimension and row.get("label") == label:
            try:
                return int(row.get("count", 0))
            except (TypeError, ValueError):
                return 0
    return 0


def _conflict_count(rows: list[dict[str, Any]], dimension: str, label: str) -> int:
    for row in rows:
        if row.get("dimension") == dimension and row.get("label") == label:
            try:
                return int(row.get("count", 0))
            except (TypeError, ValueError):
                return 0
    return 0


def _agent_eval_table(
    stats: dict[str, Any],
    abstention_rows: list[dict[str, Any]],
    conflict_rows: list[dict[str, Any]],
    aggregation_rows: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    total = int(stats["total"])
    actionable = int(stats["actionable"])
    abstained = int(stats["abstained"])
    high_risk_conflict = _conflict_count(conflict_rows, "risk_level", "high")
    total_conflicts = _conflict_count(conflict_rows, "overall", "total_conflict_rows")
    conflict_cases = _conflict_count(conflict_rows, "overall", "conflict_cases")
    missing_density = _lookup_count(abstention_rows, "abstention_reason", "missing_nodule_density")
    missing_size = _lookup_count(abstention_rows, "abstention_reason", "missing_nodule_size")
    no_nodule = _lookup_count(abstention_rows, "abstention_reason", "no_structured_nodule")
    low_risk_appendix_delta = ""
    for row in aggregation_rows:
        if row.get("strategy") == "confidence_gated_same_note_union":
            low_risk_appendix_delta = row.get("actionable_delta", "")

    rows = [
        _metric_row("Full set", f"{total}", total, "", "", "conservative v2 cases"),
        _metric_row("Actionable coverage", f"{actionable}/{total}", actionable, total, _rate(actionable, total), "hard-rule terminal recommendations"),
        _metric_row("Abstention", f"{abstained}/{total}", abstained, total, _rate(abstained, total), "not an error; critical fact missing"),
        _metric_row("Schema valid", f"{stats['schema_valid']}/{total}", stats["schema_valid"], total, _rate(stats["schema_valid"], total), "recommendation schema"),
        _metric_row("Guideline anchors", f"{stats['anchor_nonempty']}/{total}", stats["anchor_nonempty"], total, _rate(stats["anchor_nonempty"], total), "anchors bound to graph edge/node"),
        _metric_row("Reasoning paths", f"{stats['reasoning_nonempty']}/{total}", stats["reasoning_nonempty"], total, _rate(stats["reasoning_nonempty"], total), "actual graph execution trace"),
        _metric_row("Decision paths", f"{stats['decision_nonempty']}/{total}", stats["decision_nonempty"], total, _rate(stats["decision_nonempty"], total), "visited transition path"),
        _metric_row("Missing density abstention", f"{missing_density}/{total}", missing_density, total, _rate(missing_density, total), "density is not defaulted to solid"),
        _metric_row("Missing size abstention", f"{missing_size}/{total}", missing_size, total, _rate(missing_size, total), "has-size probability is not size_mm"),
        _metric_row("No structured nodule abstention", f"{no_nodule}/{total}", no_nodule, total, _rate(no_nodule, total), "no reliable structured nodule candidate"),
        _metric_row("Conflict rows", f"{total_conflicts}", total_conflicts, "", "", f"{conflict_cases} cases affected"),
        _metric_row("High-risk density conflicts", f"{high_risk_conflict}", high_risk_conflict, total_conflicts, _rate(high_risk_conflict, total_conflicts), "manual audit before aggregation"),
        _metric_row("Official aggregation adopted", "no", "", "", "", "same-case and dominant size-first remain appendix diagnostics"),
        _metric_row("Low-risk appendix actionable delta", low_risk_appendix_delta, "", "", "", "confidence-gated same-note union diagnostic only"),
        _metric_row("Learned performance metric", "not_reported", "", "", "", "CDSG-generated strong-silver labels are not fair labels for CDSG accuracy/F1"),
    ]
    return rows


def _latex_escape(value: Any) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def _write_latex_table(path: Path, rows: list[dict[str, Any]], columns: list[str], caption: str, label: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    colspec = "l" * len(columns)
    with path.open("w", encoding="utf-8", buffering=1) as fp:
        fp.write("% Auto-generated by scripts/phaseA3/evaluate_cdsg_hard_match_agent.py\n")
        fp.write("\\begin{table}[htbp]\n")
        fp.write("\\centering\n")
        fp.write("\\scriptsize\n")
        fp.write(f"\\caption{{{_latex_escape(caption)}}}\n")
        fp.write(f"\\label{{{_latex_escape(label)}}}\n")
        fp.write(f"\\begin{{tabular}}{{{colspec}}}\n")
        fp.write("\\hline\n")
        fp.write(" & ".join(_latex_escape(col) for col in columns) + " \\\\\n")
        fp.write("\\hline\n")
        for row in rows:
            fp.write(" & ".join(_latex_escape(row.get(col, "")) for col in columns) + " \\\\\n")
        fp.write("\\hline\n")
        fp.write("\\end{tabular}\n")
        fp.write("\\end{table}\n")
        fp.flush()


def _write_all_latex(
    latex_dir: Path,
    table_payloads: dict[str, tuple[list[dict[str, Any]], list[str], str, str]],
) -> None:
    for name, (rows, columns, caption, label) in table_payloads.items():
        _write_latex_table(latex_dir / f"{name}.tex", rows, columns, caption, label)


def _write_report(
    path: Path,
    stats: dict[str, Any],
    abstention_rows: list[dict[str, Any]],
    conflict_rows: list[dict[str, Any]],
    aggregation_rows: list[dict[str, Any]],
    output_dir: Path,
    latex_dir: Path,
) -> None:
    total = int(stats["total"])
    actionable = int(stats["actionable"])
    abstained = int(stats["abstained"])
    missing_density = _lookup_count(abstention_rows, "abstention_reason", "missing_nodule_density")
    missing_size = _lookup_count(abstention_rows, "abstention_reason", "missing_nodule_size")
    no_nodule = _lookup_count(abstention_rows, "abstention_reason", "no_structured_nodule")
    conflict_total = _conflict_count(conflict_rows, "overall", "total_conflict_rows")
    conflict_cases = _conflict_count(conflict_rows, "overall", "conflict_cases")
    high_risk = _conflict_count(conflict_rows, "risk_level", "high")
    same_case = next((row for row in aggregation_rows if row.get("strategy") == "same_case_union"), {})
    dominant = next((row for row in aggregation_rows if row.get("strategy") == "dominant_size_density_nearest"), {})
    gated = next((row for row in aggregation_rows if row.get("strategy") == "confidence_gated_same_note_union"), {})

    lines = [
        "# M3-3A CDSG Hard-Match Deterministic Evaluation",
        "",
        "## 定位",
        "",
        "M3-3A 是 deterministic agent evaluation，不是 learned-model 主实验。本阶段评估的是 conservative CDSG hard-match agent 在当前 v2 case bundle 上能否给出结构化、可追踪、带指南锚点的确定性输出，以及它在关键事实缺失时是否按设计 abstain。strong-silver label 由同一个 CDSG / rule engine 生成，因此不能被当作公平 gold label 来报告 Accuracy、F1 或 learned-model 性能。",
        "",
        "## 主要结果",
        "",
        f"- Full set: {total} cases。",
        f"- Actionable: {actionable}/{total} ({_pct(actionable, total)})。",
        f"- Abstention: {abstained}/{total} ({_pct(abstained, total)})。",
        f"- Schema valid: {stats['schema_valid']}/{total} ({_pct(stats['schema_valid'], total)})。",
        f"- Guideline anchor non-empty: {stats['anchor_nonempty']}/{total} ({_pct(stats['anchor_nonempty'], total)})。",
        f"- Reasoning path non-empty: {stats['reasoning_nonempty']}/{total} ({_pct(stats['reasoning_nonempty'], total)})。",
        f"- Decision path non-empty: {stats['decision_nonempty']}/{total} ({_pct(stats['decision_nonempty'], total)})。",
        "",
        "## Abstention 分解",
        "",
        f"- missing_density: {missing_density} cases。",
        f"- missing_size: {missing_size} cases。",
        f"- no_structured_nodule: {no_nodule} cases。",
        "",
        "这些 abstention 是 conservative CDSG 的预期行为：明确的 size / density / location 等结构化事实走符号硬匹配；关键事实缺失时，不允许自由生成或默认补全。",
        "",
        "## 为什么不采用 aggregation",
        "",
        f"- same-case union 可将 actionable 提高 {same_case.get('actionable_delta', '')}，但 high-risk candidates = {same_case.get('high_risk_candidates', '')}，存在跨 mention / 跨结节错配风险。",
        f"- dominant size-first + density-nearest 可将 actionable 提高 {dominant.get('actionable_delta', '')}，但 high-risk candidates = {dominant.get('high_risk_candidates', '')}，同样不适合进入正式 conservative v2。",
        f"- confidence-gated same-note union 只带来 actionable_delta = {gated.get('actionable_delta', '')}，且仍属于启发式弱合并；本轮仅作为 appendix diagnostic，不覆盖正式 v2。",
        "",
        "## 为什么不能默认补事实",
        "",
        "- missing density 不能默认 solid。solid / ground-glass / part-solid 会直接改变 Lung-RADS 路由、category 和 follow-up interval；默认 solid 会把未知事实伪装成确定事实，破坏 CDSG 的 guideline anchor 与 reasoning path 可信度。",
        "- size_mm 缺失不能用 has-size 概率补。has-size 只表示文本中可能存在尺寸表达，不是可用于阈值判断的毫米数值；Lung-RADS hard-rule 需要明确的 size_mm 才能进入阈值边。",
        "",
        "## 当前优势",
        "",
        "- 输出全部保留标准 schema、guideline anchor、reasoning path 和 decision path。",
        "- 推荐来自 CDSG 终态节点或 abstention 节点，不来自自由文本生成。",
        "- 对关键事实缺失采取 conservative abstention，避免 under-follow-up 或 hallucinated recommendation。",
        "",
        "## 当前限制",
        "",
        f"- Actionable coverage 仅 {actionable}/{total}，主要受 density 和 size 结构化事实缺失限制。",
        f"- Conflict rows = {conflict_total}，覆盖 {conflict_cases} cases；其中 high-risk density conflicts = {high_risk}，需要人工审查或更安全的 mention-to-nodule linking。",
        "- 后续若要提升覆盖率，应优先设计人工 audit set、soft matching 或受约束的事实恢复，而不是直接进入 learned-model 主实验。",
        "",
        "## 输出表格",
        "",
        f"- CSV: `{output_dir}`",
        f"- LaTeX: `{latex_dir}`",
        "",
        "## 下一步判断",
        "",
        "可以进入 M3-3B：人工 audit set 设计或 soft matching 设计。当前不建议进入 learned-model 主实验，因为可行动样本只有 76 条且 strong-silver label 来自 CDSG 自身，不能支撑公平性能表。",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate M3-3A CDSG hard-match deterministic agent.")
    parser.add_argument("--strong-silver", default="outputs/phaseA3/datasets/module3_strong_silver_v2.jsonl")
    parser.add_argument("--strong-silver-summary", default="outputs/phaseA3/tables/module3_strong_silver_v2_summary.csv")
    parser.add_argument("--label-distribution", default="outputs/phaseA3/tables/module3_strong_silver_v2_label_distribution.csv")
    parser.add_argument("--abstention-audit", default="outputs/phaseA3/tables/module3_abstention_case_audit.csv")
    parser.add_argument("--conflict-summary", default="outputs/phaseA3/tables/module3_candidate_conflict_summary.csv")
    parser.add_argument("--aggregation-simulation", default="outputs/phaseA3/tables/module3_fact_aggregation_simulation.csv")
    parser.add_argument("--output-dir", default="outputs/phaseA3/final_tables_m3a")
    parser.add_argument("--latex-dir", default="outputs/phaseA3/final_tables_latex_m3a")
    parser.add_argument("--report", default="reports/module3_cdsg_hard_match_evaluation.md")
    args = parser.parse_args()

    strong_silver_path = Path(args.strong_silver)
    if not strong_silver_path.exists():
        raise FileNotFoundError(f"missing strong-silver input: {strong_silver_path}")

    records = _load_jsonl(strong_silver_path)
    _ = _load_csv(Path(args.strong_silver_summary))
    _ = _load_csv(Path(args.label_distribution))
    _ = _load_csv(Path(args.abstention_audit))
    conflict_input = _load_csv(Path(args.conflict_summary))
    aggregation_input = _load_csv(Path(args.aggregation_simulation))

    output_dir = Path(args.output_dir)
    latex_dir = Path(args.latex_dir)

    coverage_rows, stats = _coverage_summary(records)
    label_rows: list[dict[str, Any]] = []
    label_dimensions = [
        ("recommendation_level", "recommendation_level"),
        ("lung_rads_category", "lung_rads_category"),
        ("risk_category", "risk_category"),
        ("evidence_quality_overall", "evidence_quality_overall"),
    ]
    label_rows.extend(_distribution_rows(records, stats["total"], "full_set", label_dimensions))
    label_rows.extend(_distribution_rows(stats["actionable_rows"], stats["total"], "actionable_subset", label_dimensions))
    abstention_rows = _abstention_rows(records, stats["total"])
    conflict_rows = _conflict_rows(conflict_input)
    aggregation_rows = _aggregation_appendix_rows(aggregation_input)
    agent_eval_rows = _agent_eval_table(stats, abstention_rows, conflict_rows, aggregation_rows)

    coverage_fields = ["metric", "value", "count", "denominator", "rate", "note"]
    label_fields = ["scope", "dimension", "label", "count", "fraction_within_scope", "fraction_of_total"]
    abstention_fields = ["dimension", "label", "count", "fraction_of_abstentions", "fraction_of_total"]
    conflict_fields = ["dimension", "label", "count", "interpretation"]
    aggregation_fields = list(aggregation_rows[0].keys()) if aggregation_rows else ["strategy"]
    eval_fields = ["metric", "value", "count", "denominator", "rate", "note"]

    outputs = {
        "cdsg_coverage_summary": (coverage_rows, coverage_fields, "M3-3A CDSG Coverage Summary", "tab:m3a_cdsg_coverage"),
        "actionable_label_distribution": (label_rows, label_fields, "M3-3A Label and Evidence Distribution", "tab:m3a_label_distribution"),
        "abstention_breakdown": (abstention_rows, abstention_fields, "M3-3A Abstention Breakdown", "tab:m3a_abstention_breakdown"),
        "conflict_risk_summary": (conflict_rows, conflict_fields, "M3-3A Conflict Risk Summary", "tab:m3a_conflict_risk"),
        "aggregation_simulation_appendix": (aggregation_rows, aggregation_fields, "M3-3A Aggregation Simulation Appendix", "tab:m3a_aggregation_appendix"),
        "cdsg_agent_evaluation_table": (agent_eval_rows, eval_fields, "M3-3A CDSG Agent Evaluation Table", "tab:m3a_agent_evaluation"),
    }

    for name, (rows, fields, _, _) in outputs.items():
        _write_csv(output_dir / f"{name}.csv", rows, fields)
    _write_all_latex(latex_dir, outputs)
    _write_report(Path(args.report), stats, abstention_rows, conflict_rows, aggregation_rows, output_dir, latex_dir)

    print(
        json.dumps(
            {
                "total_cases": stats["total"],
                "actionable": stats["actionable"],
                "abstention": stats["abstained"],
                "schema_valid_rate": _rate(stats["schema_valid"], stats["total"]),
                "guideline_anchor_nonempty_rate": _rate(stats["anchor_nonempty"], stats["total"]),
                "reasoning_path_nonempty_rate": _rate(stats["reasoning_nonempty"], stats["total"]),
                "decision_path_nonempty_rate": _rate(stats["decision_nonempty"], stats["total"]),
                "output_dir": str(output_dir),
                "latex_dir": str(latex_dir),
                "report": args.report,
            },
            ensure_ascii=False,
            sort_keys=True,
        ),
        flush=True,
    )


if __name__ == "__main__":
    main()
